In [3]:
import pandas as pd 
import numpy as np



In [81]:
df = pd.read_csv("C:/Users/anura/Downloads/breast+cancer+wisconsin+diagnostic(1)/wdbc.data")
df


842302  M  17.99  10.38   122.8    1001   0.1184   0.2776   0.3001  \
0      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
1    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
2    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
3    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
4      843786  M  12.45  15.70   82.57   477.1  0.12780  0.17000  0.15780   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
563    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
564    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
565    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
566    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
567     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

      0.1471  ...   25.38  17.33   184.6    2019   0.1622   0.6656  0.7119  \
0    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
1    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
2    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
3    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
4    0.08089  ...  15.470  23.75  103.40   741.6  0.17910  0.52490  0.5355   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
563  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
564  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
565  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
566  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
567  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

     0.2654  0.4601   0.1189  
0    0.1860  0.2750  0.08902  
1    0.2430  0.3613  0.08758  
2    0.2575  0.6638  0.17300  
3    0.1625  0.2364  0.07678  
4    0.1741  0.3985  0.12440  
..      ...     ...      ...  
563  0.2216  0.2060  0.07115  
564  0.1628  0.2572  0.06637  
565  0.1418  0.2218  0.07820  
566  0.2650  0.4087  0.12400  
567  0.0000  0.2871  0.07039  

[568 rows x 32 columns]

In [158]:

df.info

<bound method DataFrame.info of        842302  M  17.99  10.38   122.8    1001   0.1184   0.2776   0.3001  \
0      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
1    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
2    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
3    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
4      843786  M  12.45  15.70   82.57   477.1  0.12780  0.17000  0.15780   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
563    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
564    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
565    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
566    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
567     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

      0.1471  ...   25.38  17.33   184.6   

In [112]:
x = df.iloc[:,2:32].values
y = df.iloc[:,1].values


In [113]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,

In [114]:
 from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 0)

In [99]:
#KNN Model


In [75]:
from sklearn.neighbors import KNeighborsClassifier

In [76]:
knn = KNeighborsClassifier()

In [77]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [68]:
knn_y_pred = knn.predict(x_test)

In [69]:
from sklearn.metrics import accuracy_score

In [71]:
accuracy_score(knn_y_pred,y_test)

0.9084507042253521

In [115]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()


In [116]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [117]:
y_pred = knn.predict(x_test)

In [118]:
from sklearn.metrics import accuracy_score

In [121]:
accuracy_score(y_test,y_pred)

0.9225352112676056

In [123]:
from sklearn.linear_model import LogisticRegression

In [156]:
lre = LogisticRegression(random_state = 1) 

In [157]:
lre.fit(x_train,y_train)

C:\Users\anura\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=1)

In [127]:
y_pred = lre.predict(x_test)

In [131]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [133]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[88,  4],
       [ 7, 43]], dtype=int64)

In [135]:
acs = accuracy_score(y_test,y_pred)
acs

0.9225352112676056

In [139]:
from sklearn import svm

In [142]:
classifier = svm.SVC(kernel = 'linear',random_state = 0)

In [143]:
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [144]:
y_predi = classifier.predict(x_test)

In [145]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [146]:
cmi = confusion_matrix(y_test,y_predi)
cmi

array([[91,  1],
       [ 6, 44]], dtype=int64)

In [147]:
ac = accuracy_score(y_test,y_predi)
ac

0.9507042253521126

In [148]:
from sklearn.naive_bayes import GaussianNB

In [149]:
gnb = GaussianNB()

In [150]:
gnb.fit(x_train,y_train)

GaussianNB()

In [151]:
gnb_y_pred = gnb.predict(x_test)

In [152]:
cmi = confusion_matrix(y_test,gnb_y_pred)
cmi

array([[89,  3],
       [ 6, 44]], dtype=int64)

In [153]:
ac = accuracy_score(y_test,gnb_y_pred)
ac

0.9366197183098591